### ISSUE TITLE
Output signal equal input for reverberant speech mixture of 2 speakers

### ISSUE THREAD

**Issue by hananbo26** [alibabasglab/MossFormer#1]
Hi,
Thanks for sharing your work.
I have installed the model scope and managed to separate the example mixture.
But when I use my recording of an 8k reverberant mixture as input to the network, it does nothing - the output signals are equal to the input. 
I may be missing something. Can the example network handle reverberant signals? Do I need to normalize the signal before feeding them to the network? Is there another reason that can explain why it is not working?

**Comment by alibabasglab** [comment]
Hi, 
Thanks for trying our separation model. Yes, you are right that this released model was only trained on clean mixtures. Therefore, it won't support reverberant mixture. We also mentioned the limitation of this model in our description. We will update the model with supporting reverberant mixture later. Also you may try to finetune this model using reverberant mixtures and their clean targets.

**Comment by hananbo26** [comment]
Thanks.
